In [4]:
# if i increase all product price by 1.10
import numpy as np

In [5]:
prices = np.array([100,200,300,400,500,600,700])
prices * 1.10

array([110., 220., 330., 440., 550., 660., 770.])

In [6]:
# BROADCASTING
arr = np.array([[10,20,30] ,
               [23,24,25]])
arr + 5

array([[15, 25, 35],
       [28, 29, 30]])

In [7]:
# if size differ hoga toh error ayegaaa issme nhi hai par
arr = np.array([[10,20,30] , [21,23,26]])
arr2 = np.array([5,6,7])
result = arr + arr2
print(result)

[[15 26 37]
 [26 29 33]]


In [8]:
# INDEXING AND SLICING

arr = np.array([10,20,30,40,50])
arr[2]

np.int64(30)

In [9]:
arr[1:3]

array([20, 30])

In [10]:
arr[1:5:2]

array([20, 40])

In [11]:
arr[1:4]

array([20, 30, 40])

In [39]:
# FIRST QUESTION


sales_day1 = np.array([120,85,60])
sales_day2 = np.array([150,90,75])

result = sales_day1 + sales_day2
print(result)

[270 175 135]


In [13]:
result = sales_day1 + sales_day2
print(result)

[270 175 135]


In [14]:
percentage = (sales_day2 - sales_day1) / sales_day1 * 100
arr = np.array(percentage)
print(arr)

[25.          5.88235294 25.        ]


In [15]:
# argmax sai index aata hai , max sai value aati hai
max = arr[::].argmax()
print(max)

0


In [16]:
# SECOND QUESTION

temps = np.array([[25,28,30],[22,24,26],[30,32,33],[27,29,31],[20,21,23]])

In [17]:
temps = temps*9/5 + 32

In [18]:
print(temps)

[[77.  82.4 86. ]
 [71.6 75.2 78.8]
 [86.  89.6 91.4]
 [80.6 84.2 87.8]
 [68.  69.8 73.4]]


In [19]:
arr = np.array([1,-1,0])
temps + arr

array([[78. , 81.4, 86. ],
       [72.6, 74.2, 78.8],
       [87. , 88.6, 91.4],
       [81.6, 83.2, 87.8],
       [69. , 68.8, 73.4]])

In [20]:
bp = np.array([[120,80],[135,85],[140,90],[110,70],[125,75]])

print(bp)

[[120  80]
 [135  85]
 [140  90]
 [110  70]
 [125  75]]


In [21]:
bp[:,0]

array([120, 135, 140, 110, 125])

In [22]:
arr = np.array(bp[:,0])
arr

array([120, 135, 140, 110, 125])

In [23]:
patients = arr > 130
patients

array([False,  True,  True, False, False])

In [24]:
distolic_values = np.array(bp[:,1])
distolic_values


array([80, 85, 90, 70, 75])

In [25]:
distolic_values[distolic_values < 80] = 80
distolic_values


array([80, 85, 90, 80, 80])

In [26]:
yields = np.array([[2.5,3.0,1.8],[2.8,3.2,2.0],[3.1,2.9,2.2],[2.6,3.1,1.9]])
yields

array([[2.5, 3. , 1.8],
       [2.8, 3.2, 2. ],
       [3.1, 2.9, 2.2],
       [2.6, 3.1, 1.9]])

In [27]:
arr = np.array([0.2,0.3,0.1])
updated = np.array(yields[1,:] + arr)
yields[1,:] = updated
yields

array([[2.5, 3. , 1.8],
       [3. , 3.5, 2.1],
       [3.1, 2.9, 2.2],
       [2.6, 3.1, 1.9]])

In [28]:
arr = np.array(yields[3,:] * 1.1)
yields[3,:] = arr
yields

array([[2.5 , 3.  , 1.8 ],
       [3.  , 3.5 , 2.1 ],
       [3.1 , 2.9 , 2.2 ],
       [2.86, 3.41, 2.09]])

In [29]:
matrix = np.array(yields[0,:] + yields[1,:] + yields[2,:] + yields[3,:])
matrix

array([11.46, 12.81,  8.19])

In [30]:
max = matrix[::].argmax()
max

np.int64(1)

In [31]:
scores = np.array([[85,78,92],[88,74,90],[70,65,80],[95,89,96]])
scores

array([[85, 78, 92],
       [88, 74, 90],
       [70, 65, 80],
       [95, 89, 96]])

In [32]:
matrix = np.array(scores[:,0] + scores[:,1] + scores[:,2] )
matrix

array([255, 252, 215, 280])

In [33]:
top2_indices = np.argsort(matrix)[-2:][::-1]  
print(top2_indices)


[3 0]


In [34]:
scores[:,0]

array([85, 88, 70, 95])

In [35]:
arr = np.array(scores[:,2])
arr

array([92, 90, 80, 96])

In [38]:
# boolean indexing
arr[arr > 90]

array([92, 96])