In [23]:
# SCENARIO BASED QUESTIONS

# Scenario : FARM CROP YIELD ANALYSIS
# 3 CROPS - WHEAT , RICE , CORN 
# 4 SEASON - SPRING , SUMMER , AUTUMN , WINTER 

import numpy as np

In [24]:
# Create a 2D array representing crop yields for 3 crops across 4 seasons.
# - Rows = crops
# - Columns = seasons
    
matrix = np.array([[10,233,23,23] , [34,34,524,65] , [34,645,76,87]])
matrix

array([[ 10, 233,  23,  23],
       [ 34,  34, 524,  65],
       [ 34, 645,  76,  87]])

In [25]:
# Increase all yields by 10% to account for improved irrigation.
updated = np.array(matrix * 0.1)
updated

array([[ 1. , 23.3,  2.3,  2.3],
       [ 3.4,  3.4, 52.4,  6.5],
       [ 3.4, 64.5,  7.6,  8.7]])

In [26]:
# Extract only Wheat’s yields (the first crop).
updated[0,:]

array([ 1. , 23.3,  2.3,  2.3])

In [27]:
# Find the average yield per crop across all seasons.
avg = updated.mean(axis=1)
avg

array([ 7.225, 16.425, 21.05 ])

In [30]:
 # Identify yields greater than 3000 kg
updated[updated>50]

array([52.4, 64.5])

In [67]:
# factory production analysis 

In [62]:
matrix = np.array([[120,233,288,23] , [364,34,524,689] , [34,785,76,867]])
matrix

array([[120, 233, 288,  23],
       [364,  34, 524, 689],
       [ 34, 785,  76, 867]])

In [63]:
updated = np.array(matrix * 0.05)
updated

array([[ 6.  , 11.65, 14.4 ,  1.15],
       [18.2 ,  1.7 , 26.2 , 34.45],
       [ 1.7 , 39.25,  3.8 , 43.35]])

In [64]:
updated[0,:]

array([ 6.  , 11.65, 14.4 ,  1.15])

In [65]:
avg = updated.mean(axis=1)
avg

array([ 8.3   , 20.1375, 22.025 ])

In [66]:
updated[updated>5]

array([ 6.  , 11.65, 14.4 , 18.2 , 26.2 , 34.45, 39.25, 43.35])